[package]
name = "pokeplanet-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
pokeplanet-proto.workspace = true
anyhow.workspace = true
sha2 = "0.10"
quinn.workspace = true
rustls.workspace = true
rustls-pemfile.workspace = true
serde.workspace = true
tokio.workspace = true
libc = "0.2"
tracing.workspace = true
tracing-subscriber.workspace = true
rand.workspace = true

axum = "0.8"
serde_json = "1"
tokio-postgres = { version = "0.7", features = ["with-serde_json-1"] }
deadpool-postgres = "0.14"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
tokio-rustls = { version = "0.26", default-features = false, features = ["ring"] }
webpki-roots = "0.26"
urlencoding = "2"
